image:                                                                                                                                                                            
  repo: robotshop                                                                                                                                                                   
  version: latest
  pullPolicy: IfNotPresent                                                                                                                                                          
                                                                                                                                                                                    
nodeport: false

redis:
  storageClassName: local-path
