image:
  repo: abadnaseer24
  version: latest
  pullPolicy: IfNotPresent

nodeport: false

web:
  replicaCount: 2
  imageTag: latest

cart:
  imageTag: ec3d751

catalogue:
  imageTag: ec3d751

dispatch:
  imageTag: 4422f46

mongodb:
  imageTag: ec3d751

mysql:
  imageTag: ec3d751

payment:
  imageTag: ec3d751

ratings:
  imageTag: ec3d751

shipping:
  imageTag: latest

user:
  imageTag: ec3d751

redis:
  storageClassName: local-path
