image:                                                                                                                                                                            
  repo: abadnaseer24
  version: 8f5e977
  pullPolicy: IfNotPresent                                                                                                                                                          
                                                                                                                                                                                    
nodeport: false

web:                                                                                                                                                                              
  replicaCount: 2

redis:
  storageClassName: local-path
