image:
  repo: abadnaseer24
  version: latest
  pullPolicy: IfNotPresent

nodeport: false

web:
  replicaCount: 2
  imageTag: latest

cart:
  imageTag: latest

catalogue:
  imageTag: latest

dispatch:
  imageTag: latest

mongodb:
  imageTag: latest

mysql:
  imageTag: latest

payment:
  imageTag: latest

ratings:
  imageTag: latest

shipping:
  imageTag: latest

user:
  imageTag: latest

redis:
  storageClassName: local-path
